language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Shadownc"
  - git config user.email "365172043@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/Shadownc/Shadownc.github.io.git" master:master
# E: Build LifeCycle

#branches:
#  only:
#    - blogTS
env:
 global:
   - GH_REF: github.com/Shadownc/Shadownc.github.io.git