name: blogTS deployment

on:
  push:
    branches:
      - master # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install dependencies & Generate static files
        run: |
          node -v
          npm i -g hexo-cli
          npm i
          hexo clean
          hexo g
      - name: Deploy to Github Pages
        env:
          GIT_NAME: Shadownc
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          REPO: github.com/Shadownc/Shadownc.github.io
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ./public && git init && git add .
          git config --global user.name $GIT_NAME
          git config --global user.email $GIT_EMAIL
          git commit -m "update"
          git push --force --quiet "https://$GH_TOKEN@$REPO" master:master
